/**
 * Created by ling xue on 2016/3/2.
 */

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1 ;
var USER_STATUS_NOT_ACTIVE = 0;


/**
 * SMS SEND TYPE
 */
var SMS_REG_TYPE = 1;
var SMS_PSWD_TYPE = 2;

module.exports = {
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    SMS_REG_TYPE : SMS_REG_TYPE ,
    SMS_PSWD_TYPE : SMS_PSWD_TYPE
}
